name: Pokedex

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Einrichten von Linting-, Test- und Build-Schritten
        run: echo "Einrichten von Linting-, Test- und Build-Schritten"

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Code Linting
        run: npm run eslint
